server:
  port: 443
  context-path: /cms
  ssl:
    key-alias: tomcat #别名
    key-store: classpath:server.keystore
    key-store-type: JKS
    key-store-password: 123456
    enabled: true
spring:
  datasource:
    url: jdbc:mysql://39.107.242.109:3306/cms?characterEncodeing=UTF-8&useSSL=false
    #url: jdbc:mysql://localhost:3306/demo?characterEncodeing=UTF-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #Driud连接池
    initialSize: '5' #初始化连接大小
    minIdle: '5'     #最小连接池数量
    maxActive: '20'  #最大活跃数
    # 配置获取连接等待超时的时间
    maxWait: '3000'
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: '60000'
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: '300000'
    validationQuery: select version(); #测试连接
    testWhileIdle: 'true'  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: 'false'  #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: 'false'  #归还连接时执行检测，建议关闭，影响性能
    #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    poolPreparedStatements: 'true'
    maxPoolPreparedStatementPerConnectionSize: '100'
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: 'stat,wall,log4j'
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: 'druid.stat.mergeSql: true, druid.stat.slowSqlMillis: 5000'
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: 'true'
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: detect
  redis:
    host: 39.107.242.109
    port: 6379
    password: admin
    timeout: 600000
    database: 0
  cache:
    type: redis
  rabbitmq:
    host: 39.107.242.109
    port: 5672
    username: guest
    password: guest
mybatis:
  type-aliases-package: com.fzy.entity
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
wx:
  appId: wx44d4961e877d0cf6
  secret: 1c6b9d840b6a1779b446dedcac502939
  url: https://api.weixin.qq.com/sns/jscode2session
  grant_type: authorization_code